[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{access='read',path='.'}]
solc = "0.8.19"
via_ir = true
optimizer = true
optimizer_runs = 1000

[profile.test]
ffi = true
verbosity = 2
